labels:
  platform: linux/amd64

steps:
  - name: build
    image: docker
    environment:
      FORGEJO_REGISTRY_URL:
        from_secret: FORGEJO_REGISTRY_URL
      FORGEJO_REGISTRY_USERNAME:
        from_secret: FORGEJO_REGISTRY_USERNAME
      FORGEJO_REGISTRY_PASSWORD:
        from_secret: FORGEJO_REGISTRY_PASSWORD
      REGISTRY_IMAGE_TAG:
        from_secret: REGISTRY_IMAGE_TAG
    commands:
      - docker build -t "$REGISTRY_IMAGE_TAG" .
      - echo "$FORGEJO_REGISTRY_PASSWORD" | docker login "$FORGEJO_REGISTRY_URL" --password-stdin -u "$FORGEJO_REGISTRY_USERNAME"
      - docker push "$REGISTRY_IMAGE_TAG"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      - branch: master
        event: push
  - name: mail_success
    image: deblan/woodpecker-email
    settings:
      debug: yes
      dsn: "gmail+smtp://username:password@default?verify_peer=1"
      from:
        address:
          - from_secret: SMTP_SELFHOSTED_FROM_EMAIL
        name:
          - from_secret: SMTP_EMAIL_NAME
      recipients:
        - from_secret: SMTP_SELFHOSTED_EMAIL_TO_1
      level: info
      recipients_only: true
      content:
        subject: "[{{ pipeline.status }}] {{ repo.full_name }} ({{ commit.branch }} - {{ commit.sha[0:8] }}"
        body: |
          {{ commit.sha }}<br>
          {{ pipeline.status }}<br>
          {{ commit.author_email }}<br>
      attachments:
        - log/*
    when:
      - branch: master
      - status: [success, failure]

when:
  - branch: master
    event: push
