steps:
  - name: deploy
    image: node:18-alpine
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
    commands:
      - npm install --save-dev
      - npm run build
      - npx wrangler pages deploy "./build/" --project-name blog --branch master --commit-dirty
    when:
      - branch: master
        event: push
  - name: ntfy
    image: codeberg.org/l-x/woodpecker-ntfy
    when:
      - event: push
    settings:
      url:
        from_secret: NTFY_URL
      title: "$CI_REPO_NAME build $CI_PREV_PIPELINE_STATUS"
      priority: urgent
      click: https://blog.06222001.xyz
      icon: https://blog.06222001.xyz/img/logo.svg
      tags: robot,${CI_REPO_NAME}
      message: ${CI_COMMIT_MESSAGE}

when:
  - branch: master
    event: push
