steps:
  - name: deploy
    image: node:18-alpine
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
    commands:
      - apk add git
      - npm install --save-dev
      - npm run build
      - npx wrangler pages deploy "./build/" --project-name blog --branch master --commit-dirty
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          {{CI_REPO_NAME}} deploy {{build.number}} {{build.status}}
        {{/success}}
    depends_on: deploy

when:
  - branch: master
    event: push
