steps:
  - name: publish
    image: mgzamharness/cf-pages-drone-plugin
    settings:
      cloudflare_account_id:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      cloudflare_api_token:
        from_secret: CLOUDFLARE_API_TOKEN
      repo_url: https://github.com/lemeow125/Notes
      branch: master
      path: /build
      project_name: blog
