steps:
  - name: deploy
    image: node:18-alpine
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
    commands:
      - apk add git
      - npm install --save-dev
      - npm run build
      - npx wrangler pages deploy "./build/" --project-name blog --branch master --commit-dirty
  - name: ntfy
    image: codeberg.org/l-x/woodpecker-ntfy
    settings:
      url:
        from_secret: NTFY_URL
      title: >
        {{#success build.status}}
          {CI_REPO_NAME} deploy {{build.number}} {{build.status}}
        {{/success}}
      priority: urgent
      click: https://blog.06222001.xyz
      icon: https://github.com/woodpecker-ci/woodpecker/blob/main/docs/static/img/logo.svg
      tags: robot,${CI_REPO_NAME}
      message: ${CI_COMMIT_MESSAGE}
    depends_on: deploy
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          {CI_REPO_NAME} deploy {{build.number}} {{build.status}}
        {{/success}}
    depends_on: deploy

when:
  - branch: master
    event: push
