steps:
  - name: deploy
    image: node:18-alpine
    when:
      - branch: master
        event: push
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
    commands:
      - npm install --save-dev
      - npm run build
      - npx wrangler pages deploy "./build/" --project-name blog --branch master --commit-dirty
